version: "3"

services:
  redmine_db:
    restart: always
    image: mysql:5.7.28
    volumes:
      - "redmine-data:/var/lib/mysql"
    networks:
      - redmine-back-tier
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
#      MYSQL_USER: redmine
#      MYSQL_PASSWORD: redmine
  redmine:
    image: redmine

    ports:
      - "5005:3000"
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: root
      REDMINE_SECRET_KEY_BASE: root
    links:
      - redmine_db
    networks:
      - redmine-back-tier

volumes:
  redmine-data:

networks:
  redmine-back-tier: